import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const wasmBuffer = fs.readFileSync(path.join(__dirname, 'build/scorer.wasm'));
const wasmModule = await WebAssembly.instantiate(wasmBuffer, { env: { abort: () => {} } });
const ex = wasmModule.instance.exports as any;
console.log('prev:', ex.getPrev());
console.log('curr:', ex.getCurr());
console.log('mask:', ex.getMask());
console.log('visited:', ex.getVisited());
console.log('stack:', ex.getStack());
console.log('memory size:', ex.memory.buffer.byteLength);
